### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by john-b-yang**
Created PR that addresses issue #11.

Also, as one of the WebShop authors, I think "Evaluating LLMs as Agents" is a much more suitable section than tool evalaution. It is the first instantiation of a web-based setting for language agents, and has served as inspiration for later work such as AgentBench and WebArena (one of AgentBench's environments is an adaptation of WebShop).

Would you also mind adding the links for InterCode and SWE-bench to your leaderboard section when #13 is merged? Thanks.

### CODE REVIEW

**Comment by zhimin-z** [comment]
@john-b-yang That is a very good PR, but I just have one single question here. 

The leaderboard shown in their repo is mostly about (near) holistic-level benchmarking on LLM. For InterCode and SWE-bench, it seems they only care about code generation capacity. Is that better to merge those two leaderboards into [Awesome-Code-LLM](https://github.com/huybery/Awesome-Code-LLM) instead?

**Comment by john-b-yang** [comment]
@zhimin-z I see, although to me it feels like some of the leaderboards in the updated README are fairly limited to a single task (i.e. HumanEval)?

Regarding being added to the leaderboard list, I'll leave it up to the authors. But just wanted to point it out for consideration!

**Comment by zhimin-z** [comment]
> @zhimin-z I see, although to me it feels like some of the leaderboards in the updated README are fairly limited to a single task (i.e. HumanEval)?
> 
> Regarding being added to the leaderboard list, I'll leave it up to the authors. But just wanted to point it out for consideration!

Good catch. I double confirm with HF maintainers that the HF Humaneval leaderboard is deprecated, so I removed it from https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/pull/13.

**Comment by zhimin-z** [comment]
After further examination, I've decided to add https://intercode-benchmark.github.io/ and https://huggingface.co/spaces/bigcode/bigcode-models-leaderboard in https://github.com/tjunlp-lab/Awesome-LLMs-Evaluation-Papers/pull/13, @john-b-yang

**Comment by john-b-yang** [comment]
Sweet, thanks so much @zhimin-z! Really appreciate the dialogue.

**Pull request merged**
